"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { decodeEventLog, isAddress, parseUnits } from "viem";
import { useAccount, useBalance, useChainId, useConnect, useDisconnect, useSendTransaction, useSwitchChain, useWaitForTransactionReceipt, useWriteContract } from "wagmi";
import { LogoUpload } from "../../components/logo-upload";
import { activeChain, explorerBase, factoryAddress, feeEth, feeRecipient } from "../../lib/config";
import { tokenFactoryAbi } from "../../lib/contracts";

type Stage = "idle" | "paying" | "payment_confirmed" | "deploying" | "success";

export default function Creator() {
  const [name, setName] = useState("My Token"); const [symbol, setSymbol] = useState("MTK"); const [supply, setSupply] = useState("1000000"); const [decimals, setDecimals] = useState("18");
  const [logo, setLogo] = useState<string>(); const [stage, setStage] = useState<Stage>("idle"); const [error, setError] = useState(""); const [warning, setWarning] = useState(""); const [darkMode, setDarkMode] = useState(false);
  const [paymentHash, setPaymentHash] = useState<`0x${string}`>(); const [deploymentHash, setDeploymentHash] = useState<`0x${string}`>(); const [tokenAddress, setTokenAddress] = useState(""); const [recordId, setRecordId] = useState("");
  const { address, isConnected } = useAccount(); const chainId = useChainId(); const { connect, connectors, isPending: connecting } = useConnect(); const { disconnect } = useDisconnect(); const { switchChain, isPending: switching } = useSwitchChain(); const { data: balance } = useBalance({ address });
  const { sendTransactionAsync } = useSendTransaction(); const { writeContractAsync } = useWriteContract(); const payment = useWaitForTransactionReceipt({ hash: paymentHash }); const deployment = useWaitForTransactionReceipt({ hash: deploymentHash });
  const validation = useMemo(() => { if (!name.trim()) return "Token name is required."; if (!/^[a-zA-Z0-9 ._-]{1,32}$/.test(name)) return "Name must be 1–32 letters, numbers, spaces or ._- only."; if (!/^[a-zA-Z0-9]{1,12}$/.test(symbol)) return "Symbol must be 1–12 letters or numbers."; if (!/^\d+(\.\d+)?$/.test(supply) || Number(supply) <= 0) return "Supply must be a positive number."; const d = Number(decimals); if (!Number.isInteger(d) || d < 0 || d > 18) return "Decimals must be an integer from 0 to 18."; try { parseUnits(supply, d); } catch { return "Supply has too many decimal places."; } return ""; }, [name, symbol, supply, decimals]);
  const wrongNetwork = isConnected && chainId !== activeChain.id; const insufficient = balance && feeEth ? balance.value < parseUnits(feeEth, 18) : false; const processing = stage === "paying" || stage === "deploying";
  const save = useCallback(async (payload: Record<string, unknown>) => { try { const response = await fetch(recordId ? `/api/creations/${recordId}` : "/api/creations", { method: recordId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Database error"); if (!recordId && body.record?.id) { setRecordId(body.record.id); localStorage.setItem("tokenbase.recordId", body.record.id); } } catch (cause) { setWarning(cause instanceof Error ? cause.message : "Database unavailable. Chain state remains authoritative."); } }, [recordId]);
  useEffect(() => { const p = localStorage.getItem("tokenbase.paymentHash"), d = localStorage.getItem("tokenbase.deploymentHash"), id = localStorage.getItem("tokenbase.recordId"); if (p?.startsWith("0x")) setPaymentHash(p as `0x${string}`); if (d?.startsWith("0x")) { setDeploymentHash(d as `0x${string}`); setStage("deploying"); } if (id) setRecordId(id); }, []);
  useEffect(() => { if (paymentHash) localStorage.setItem("tokenbase.paymentHash", paymentHash); }, [paymentHash]); useEffect(() => { if (deploymentHash) localStorage.setItem("tokenbase.deploymentHash", deploymentHash); }, [deploymentHash]); useEffect(() => { document.documentElement.dataset.theme = darkMode ? "dark" : ""; }, [darkMode]);
  useEffect(() => { if (payment.isSuccess && stage === "paying") { setStage("payment_confirmed"); void save({ status: "payment_confirmed", payment_tx_hash: paymentHash }); } }, [payment.isSuccess, paymentHash, save, stage]);
  useEffect(() => { if (payment.isError) { setStage("idle"); setError("Payment transaction failed on-chain. No deployment was started."); } }, [payment.isError]);
  const created = deployment.data?.logs.map(log => { try { const decoded = decodeEventLog({ abi: tokenFactoryAbi, data: log.data, topics: log.topics }); return decoded.eventName === "TokenCreated" ? String(decoded.args.token) : undefined; } catch { return undefined; } }).find(Boolean);
  useEffect(() => { if (deployment.isSuccess && created && stage !== "success") { setTokenAddress(created); setStage("success"); void save({ status: "success", contract_address: created, deployment_tx_hash: deploymentHash }); localStorage.removeItem("tokenbase.paymentHash"); localStorage.removeItem("tokenbase.deploymentHash"); } }, [created, deployment.isSuccess, deploymentHash, save, stage]);
  useEffect(() => { if (deployment.isError) { setStage("payment_confirmed"); setError("Deployment transaction failed on-chain. The confirmed tool fee was not reversed."); } }, [deployment.isError]);
  const pay = async () => { setError(""); if (!feeRecipient || !feeEth || !factoryAddress) return setError("App configuration is incomplete. Set fee, recipient and factory address in .env.local."); if (!isAddress(feeRecipient)) return setError("Fee recipient is not a valid address."); try { setStage("paying"); const hash = await sendTransactionAsync({ to: feeRecipient, value: parseUnits(feeEth, 18), chainId: activeChain.id }); setPaymentHash(hash); await save({ wallet_address: address, network: activeChain.name, token_name: name.trim(), token_symbol: symbol.trim().toUpperCase(), total_supply: supply, decimals: Number(decimals), logo_url: logo || null, payment_tx_hash: hash, status: "pending_payment" }); } catch (cause) { setStage("idle"); setError(cause instanceof Error ? cause.message : "Payment was rejected or failed."); } };
  const deploy = async () => { setError(""); if (!factoryAddress || !paymentHash) return; try { setStage("deploying"); await save({ status: "deploying" }); const hash = await writeContractAsync({ address: factoryAddress, abi: tokenFactoryAbi, functionName: "createToken", args: [name.trim(), symbol.trim().toUpperCase(), Number(decimals), parseUnits(supply, Number(decimals))], chainId: activeChain.id }); setDeploymentHash(hash); } catch (cause) { setStage("payment_confirmed"); setError(cause instanceof Error ? cause.message : "Deployment was rejected or failed."); } };
  const connectWallet = () => { const connector = connectors[0]; if (connector) void connect({ connector }); };
  const primaryAction = () => { if (!isConnected) return connectWallet(); if (stage === "idle") return void pay(); if (stage === "payment_confirmed") return void deploy(); };
  const primaryLabel = !isConnected ? "Connect Wallet" : stage === "idle" ? "Create Token" : stage === "payment_confirmed" ? "Deploy Token" : stage === "success" ? "Token Created" : "Transaction Pending";
  const canPay = Boolean(isConnected && !wrongNetwork && !validation && !processing && feeRecipient && feeEth && factoryAddress && !insufficient);

  return <main>
    <header className="site-header"><Link href="/" className="brand"><span className="mark">T</span> Tokenbase</Link><div className="header-actions"><button className="icon-button" aria-label="Toggle theme" onClick={() => setDarkMode(value => !value)}>{darkMode ? "☀" : "◐"}</button><button className="button header-connect" disabled={connecting || isConnected} onClick={connectWallet}>{isConnected ? `${address?.slice(0, 6)}…${address?.slice(-4)}` : "Connect Wallet"}</button></div></header>
    <section className="hero"><div className="hero-badge">▣&nbsp; ERC-20 on Base</div><h1>Base Token Creator</h1><p>Launch an ERC-20 on Base paying L2 fees, not mainnet ones. No Solidity, no scripts.</p></section>
    <section className="creator-card">
      <div className="form-section"><div className="form-grid"><div className="field"><label>Name</label><input placeholder="Ex: Base" value={name} maxLength={32} onChange={event => setName(event.target.value)} /></div><div className="field"><label>Symbol <span className="muted">{symbol.length}/10</span></label><input placeholder="Ex: ETH" value={symbol} maxLength={12} onChange={event => setSymbol(event.target.value.toUpperCase())} /></div><div className="field"><label>Decimals</label><input placeholder="Most tokens use 18 decimals" value={decimals} inputMode="numeric" onChange={event => setDecimals(event.target.value)} /><span className="helper">0–18 · recommended: 18</span></div><div className="field"><label>Supply</label><input placeholder="Most tokens use 1 000 000 000" value={supply} inputMode="decimal" onChange={event => setSupply(event.target.value)} /><span className="helper">Total tokens to mint at creation</span></div><div className="field full"><label>Logo <span className="optional muted">(optional)</span></label><LogoUpload onUploaded={setLogo} onError={setError} /><span className="helper">Optional server-side logo storage. The token remains standard ERC-20.</span></div></div>{validation && <div className="error" style={{ marginTop: 15 }}>{validation}</div>}</div>
      <div className="form-section"><div className="fee-row"><div className="fee-copy"><h3>Transaction Fee (%)</h3><p>Set the fee amount and the wallet to receive token transaction fees. Can be updated after initial token creation.</p></div><span className="switch" aria-hidden="true" /></div><div className="toggle-row"><div className="toggle-copy"><h3>Enable Deflation <span className="muted">(not available)</span></h3><p>Make your token deflationary by burning a percentage of the fee.</p><span className="disabled-note">Not supported by current Factory</span></div><span className="switch" aria-hidden="true" /></div><div className="toggle-row"><div className="toggle-copy"><h3>Enable Reflection <span className="muted">(not available)</span></h3><p>Automatically distribute transaction fees to reward token holders.</p><span className="disabled-note">Not supported by current Factory</span></div><span className="switch" aria-hidden="true" /></div></div>
      <div className="form-section"><div className="section-heading"><div><h2>Token Properties</h2><p>Optional contract rules available in the full tool.</p></div></div><div className="property-grid">{[["◒","Burnable","Enable the ability to permanently remove tokens from circulation by burning"],["▤","Mintable","Enable minting for your token, only the owner can mint."],["Ⅱ","Pausable","Allows pausing all token transfers and trading activity temporarily"]].map(([icon,title,description]) => <div className="property-card is-disabled" key={title}><div className="property-top"><span className="property-name">{icon}&nbsp; {title}</span><span className="property-price">Unavailable</span></div><p>{description}</p></div>)}</div></div>
      <div className="form-section"><div className="advanced">Advanced Options <span className="chevron">⌄</span></div></div>
      <div className="form-section"><div className="section-heading"><div><h2>Trading Limits</h2><p>Protection features are not enabled in the current deployment contract.</p></div></div><div className="property-grid">{[["◈","Anti whale","Set trading limits to your token to avoid whales"],["♙","Anti Bot","Prevent bots from trading your token by limiting to one trade per block"],["⊘","Blacklist","Add addresses to a blacklist that prevents them from trading the token"]].map(([icon,title,description]) => <div className="property-card is-disabled" key={title}><div className="property-top"><span className="property-name">{icon}&nbsp; {title}</span><span className="property-price">Unavailable</span></div><p>{description}</p></div>)}</div></div>
      <div className="form-section"><div className="section-heading"><div><h2>Wallet and deployment</h2><p>Connect your wallet to approve the service fee and deploy your token.</p></div></div>{wrongNetwork && <div className="notice warning">Switch to {activeChain.name} to continue. <button className="button" disabled={switching} onClick={() => switchChain({ chainId: activeChain.id })}>{switching ? "Switching…" : "Switch network"}</button></div>}{balance && <div className="helper">Wallet balance: {balance.formatted} {balance.symbol}{insufficient ? " · insufficient" : ""}</div>}{error && <div className="error" style={{ marginTop: 10 }}>{error}</div>}{warning && <div className="notice warning">Database record warning: {warning}</div>}{stage === "paying" && <div className="status"><strong>Payment pending</strong><span className="muted">Confirm the transaction in your wallet.</span>{paymentHash && <div className="mono"><a href={`${explorerBase}/tx/${paymentHash}`} target="_blank">View payment transaction ↗</a></div>}</div>}{stage === "payment_confirmed" && <div className="status"><strong>Payment confirmed</strong><span className="muted">Verified on-chain. Your token is ready for deployment.</span></div>}{stage === "deploying" && <div className="status"><strong>Deployment pending</strong><span className="muted">Waiting for the confirmed Factory event.</span>{deploymentHash && <div className="mono"><a href={`${explorerBase}/tx/${deploymentHash}`} target="_blank">View deployment transaction ↗</a></div>}</div>}{stage === "success" && <div className="status"><strong style={{ color: "var(--success)" }}>Token created successfully</strong><span className="muted">Total supply minted to your wallet.</span><div className="mono" style={{ marginTop: 10, wordBreak: "break-all" }}>{tokenAddress}</div><div className="actions"><button className="button secondary" onClick={() => navigator.clipboard.writeText(tokenAddress)}>Copy contract</button><a className="button" href={`${explorerBase}/address/${tokenAddress}`} target="_blank">View on BaseScan</a></div></div>}{stage !== "success" && <><button className="button primary-action" disabled={processing || (stage === "idle" && (!canPay && isConnected))} onClick={primaryAction}>{primaryLabel}</button><div className="total-fees">Total Fees: <strong>{feeEth || "reading…"} ETH</strong> + Gas</div></>}</div>
    </section>
    <div className="footer-note">Payments and deployments are separate user-signed transactions. No private keys or seed phrases are requested.</div>
  </main>;
}
